import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const pluginRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(pluginRoot, "..", "..");
const sourcePath = join(pluginRoot, "schemas", "workflow-policy.json");
const policy = JSON.parse(readFileSync(sourcePath, "utf8"));
const check = process.argv.includes("--check");
const canonical = (value) => {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;
  return JSON.stringify(value);
};
const sha256 = (value) => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const policyDigest = sha256(canonical(policy));

const unique = (values, name) => {
  if (!Array.isArray(values) || new Set(values).size !== values.length) throw new Error(`${name} must be a unique array`);
};
for (const name of ["flows", "statuses", "phases", "phase_order"]) unique(policy[name], name);
for (const phase of policy.phases) if (!policy.phase_labels?.[phase]) throw new Error(`phase_labels.${phase} is required`);
for (const flow of policy.flows) {
  const route = policy.route_templates?.[flow];
  if (!route || route[0] !== "route" || route.at(-1) !== "close") throw new Error(`route template ${flow} must run route -> close`);
  unique(route, `route_templates.${flow}`);
  for (const phase of route) if (!policy.phases.includes(phase)) throw new Error(`route template ${flow} contains unknown phase ${phase}`);
}

const expectedHosts = ["codex", "claude-code", "opencode", "pi", "dsh", "zcode"];
const protocol = policy.delivery_protocol;
if (!policy.policy_id || !/^\d+\.\d+\.\d+$/.test(policy.schema_version || "")) throw new Error("policy_id and semantic schema_version are required");
if (!protocol?.authority || !Array.isArray(protocol.external_actions) || !Array.isArray(protocol.evidence_required_fields) || !Array.isArray(protocol.close_gates)) {
  throw new Error("delivery_protocol is incomplete");
}
for (const gate of ["acceptance-evidence", "review-disposition", "terminal-observation"]) {
  if (!protocol.close_gates.includes(gate)) throw new Error(`delivery_protocol.close_gates is missing ${gate}`);
}
if (protocol.close_gates.includes("host-plan-or-handoff") || protocol.host_plan?.required_for_close !== false || protocol.host_plan?.role !== "advisory-runtime-projection") {
  throw new Error("host_plan must be advisory and excluded from close gates");
}
if (protocol.lifecycle_hooks?.role !== "opt-in-advisory" || protocol.lifecycle_hooks?.writes_state !== false || !Array.isArray(protocol.lifecycle_hooks?.events) || !protocol.lifecycle_hooks.events.length) {
  throw new Error("lifecycle_hooks must be an opt-in, non-writing advisory definition");
}
if (!Array.isArray(protocol.artifact_roots) || !protocol.artifact_roots.includes("plan_root")) throw new Error("delivery_protocol.artifact_roots must include plan_root");
const modes = policy.modes;
if (!modes?.profiles?.standard || !modes?.profiles?.strict || !modes.default || !modes.profiles[modes.default]) throw new Error("standard and strict policy modes are required");
if (!Array.isArray(modes.strict_escalation_signals) || !modes.strict_escalation_signals.length) throw new Error("strict escalation signals are required");
if (!Array.isArray(policy.evidence_results) || !policy.evidence_results.length) throw new Error("evidence results are required");
if (!policy.review?.severities?.length || !policy.review?.dispositions?.length || !policy.review?.fixed_point_phases?.length) throw new Error("review policy is incomplete");
const hostProfiles = policy.host_profiles;
if (!hostProfiles || typeof hostProfiles !== "object") throw new Error("host_profiles must be an object");
for (const host of expectedHosts) {
  const profile = hostProfiles[host];
  if (!profile) throw new Error(`host_profiles.${host} is required`);
  if (!['native', 'native-mcp', 'bridge', 'probe-required'].includes(profile.support)) throw new Error(`host_profiles.${host}.support is invalid`);
  if (!profile.entry || !profile.mcp || !profile.plan_sync || !profile.adapter?.format || !profile.adapter?.target) {
    throw new Error(`host_profiles.${host} is incomplete`);
  }
  if (profile.support === 'native-mcp' && !profile.adapter.template) throw new Error(`host_profiles.${host} requires an adapter template`);
}

const generatedHeader = "// Generated by scripts/generate-policy.mjs. Do not edit.\n";
const runtime = `${generatedHeader}export const POLICY = ${JSON.stringify(policy, null, 2)};\nexport const POLICY_DIGEST = ${JSON.stringify(policyDigest)};\n`;
const stateSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Delivery Control flow state",
  type: "object",
  required: ["flow_id", "revision", ...policy.required_fields, "delivery_generation", "scope_digest", "fixed_point", "mode", "policy_id", "policy_version", "policy_digest"],
  properties: {
    flow_id: { type: "string", minLength: 1 }, revision: { type: "integer", minimum: 0 },
    flow: { enum: policy.flows }, status: { enum: policy.statuses }, current_phase: { enum: policy.phases },
    next_phase: { enum: [...policy.phases, "none"] }, plan_target: { type: "string", minLength: 1 },
    terminal_condition: { type: "string", minLength: 1 }, resume_point: { type: "string", minLength: 1 },
    delivery_generation: { type: "integer", minimum: 1 }, scope_digest: { type: "string", pattern: "^sha256:[0-9a-f]{64}$" },
    mode: { enum: Object.keys(modes.profiles) }, policy_id: { const: policy.policy_id }, policy_version: { const: policy.schema_version }, policy_digest: { const: policyDigest },
    fixed_point: { type: "object", required: ["generation", "spec_digest", "implementation_digest", "review_digest"], properties: {
      generation: { type: "integer", minimum: 1 }, spec_digest: { type: ["string", "null"] }, implementation_digest: { type: ["string", "null"] }, review_digest: { type: ["string", "null"] }
    } }
  }
};
const evidenceSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema", title: "Delivery evidence", type: "object",
  required: ["evidence_id", "acceptance_ids", "type", "result", "artifact", "artifact_digest", "command_or_request_id", "observed_at", "producer", "environment", "delivery_generation", "subject_digest"],
  properties: {
    evidence_id: { type: "string", minLength: 1 }, acceptance_ids: { type: "array", minItems: 1, uniqueItems: true, items: { type: "string", minLength: 1 } },
    type: { type: "string", minLength: 1 }, result: { enum: ["passed", "verified", "accepted", "observed"] }, artifact: { type: "string", minLength: 1 },
    artifact_digest: { type: "string", pattern: "^sha256:[0-9a-f]{64}$" }, command_or_request_id: { type: "string", minLength: 1 }, observed_at: { type: "string", format: "date-time" },
    producer: { type: "string", minLength: 1 }, environment: { type: "string", minLength: 1 }, supersedes: { type: ["string", "null"] }, expires_at: { type: ["string", "null"], format: "date-time" },
    delivery_generation: { type: "integer", minimum: 1 }, subject_digest: { type: "string", pattern: "^sha256:[0-9a-f]{64}$" }
  }
};
const actionResultSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema", title: "External action result", type: "object",
  required: ["action_result_id", "authorization_id", "action", "target", "environment", "action_request_digest", "outcome", "observed_at", "producer", "result_digest", "artifact", "artifact_digest", "command_or_request_id", "delivery_generation"],
  properties: {
    action_result_id: { type: "string", minLength: 1 }, authorization_id: { type: "string", minLength: 1 }, action: { type: "string", minLength: 1 }, target: { type: "string", minLength: 1 }, environment: { type: "string", minLength: 1 },
    action_request_digest: { type: "string", pattern: "^sha256:[0-9a-f]{64}$" }, outcome: { enum: ["succeeded", "failed"] }, observed_at: { type: "string", format: "date-time" }, producer: { type: "string", minLength: 1 },
    result_digest: { type: "string", pattern: "^sha256:[0-9a-f]{64}$" }, artifact: { type: "string", minLength: 1 }, artifact_digest: { type: "string", pattern: "^sha256:[0-9a-f]{64}$" },
    command_or_request_id: { type: "string", minLength: 1 }, supersedes: { type: ["string", "null"] }, delivery_generation: { type: "integer", minimum: 1 }
  }
};
const hostCapabilities = {
  schema_version: policy.schema_version,
  policy_id: policy.policy_id,
  policy_digest: policyDigest,
  authority: "plugins/delivery-control/schemas/workflow-policy.json",
  hosts: hostProfiles
};
const generatedAdapterTemplates = new Map();
for (const [host, profile] of Object.entries(hostProfiles)) {
  if (!profile.adapter.template) continue;
  const extension = profile.adapter.format === "json" ? "json" : "yml";
  generatedAdapterTemplates.set(join(repoRoot, "adapters", host, `${host}.${extension}.template`),
    typeof profile.adapter.template === "string"
      ? profile.adapter.template
      : `${JSON.stringify(profile.adapter.template, null, 2)}\n`);
}
const outputs = new Map([
  [join(pluginRoot, "src", "policy.generated.mjs"), runtime],
  [join(pluginRoot, "schemas", "flow-state.schema.json"), `${JSON.stringify(stateSchema, null, 2)}\n`],
  [join(pluginRoot, "schemas", "evidence.schema.json"), `${JSON.stringify(evidenceSchema, null, 2)}\n`],
  [join(pluginRoot, "schemas", "external-action-result.schema.json"), `${JSON.stringify(actionResultSchema, null, 2)}\n`],
  [join(repoRoot, "skills", "engineering-workflow", "references", "state-machine.json"), `${JSON.stringify(policy, null, 2)}\n`],
  [join(repoRoot, "skills", "engineering-workflow", "references", "host-capabilities.json"), `${JSON.stringify(hostCapabilities, null, 2)}\n`],
  [join(repoRoot, "adapters", "host-capabilities.json"), `${JSON.stringify(hostCapabilities, null, 2)}\n`]
]);
for (const [path, content] of generatedAdapterTemplates) outputs.set(path, content);

const drift = [];
for (const [path, content] of outputs) {
  if (check) {
    let actual = null;
    try { actual = readFileSync(path, "utf8"); } catch {}
    if (actual !== content) drift.push(path);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf8");
  }
}
if (drift.length) {
  console.error(`Generated policy artifacts are stale:\n${drift.join("\n")}`);
  process.exitCode = 1;
} else console.log(check ? "Generated policy artifacts are current." : "Generated policy artifacts updated.");
